local CombatFramework = require(game:GetService("Players").LocalPlayer.PlayerScripts.CombatFramework)
local Camera = require(game.ReplicatedStorage.Util.CameraShaker)
Camera:Stop()
coroutine.wrap(function()
    game:GetService("RunService").Stepped:Connect(function()
        if getupvalues(CombatFramework)[2]['activeController'].timeToNextAttack then
            getupvalues(CombatFramework)[2]['activeController'].timeToNextAttack = 0
            getupvalues(CombatFramework)[2]['activeController'].hitboxMagnitude = 25
            getupvalues(CombatFramework)[2]['activeController']:attack()
        end
    end)
end)()
------------------
local CombatFramework = require(game:GetService("Players").LocalPlayer.PlayerScripts.CombatFramework)
local activeController = getupvalues(CombatFramework)[2]['activeController']
local Camera = require(game.ReplicatedStorage.Util.CameraShaker)
Camera:Stop()
spawn(function()
    game:GetService("RunService").Stepped:Connect(function()
        activeController.timeToNextAttack = 0
        activeController.hitboxMagnitude = 80
    end)
end)
spawn(function()
    game:GetService("RunService").Stepped:Connect(function()
        activeController:attack()
    end)
end)
-- https://github.com/b3styskid/MAZI-API
--------------------
local Camera = require(game.ReplicatedStorage.Util.CameraShaker)
Camera:Stop()
game:GetService("RunService").Stepped:Connect(function()
    getupvalues(require(game:GetService("Players").LocalPlayer.PlayerScripts.CombatFramework))[2]['activeController'].timeToNextAttack = 0
    getupvalues(require(game:GetService("Players").LocalPlayer.PlayerScripts.CombatFramework))[2]['activeController'].hitboxMagnitude = 80
end)
game:GetService("RunService").Stepped:Connect(function()
    pcall(function()
        getupvalues(require(game:GetService("Players").LocalPlayer.PlayerScripts.CombatFramework))[2]['activeController']:attack()
    end)
    game:GetService'VirtualUser':CaptureController()
    game:GetService'VirtualUser':Button1Down(Vector2.new(1280, 672))
end)
game:GetService("RunService").Stepped:Connect(function()
    pcall(function()
        getupvalues(require(game:GetService("Players").LocalPlayer.PlayerScripts.CombatFramework))[2]['activeController']:attack()
        game:GetService'VirtualUser':CaptureController()
        game:GetService'VirtualUser':Button1Down(Vector2.new(1280, 672))
    end)
end)
game:GetService("RunService").Stepped:Connect(function()
    pcall(function()
        getupvalues(require(game:GetService("Players").LocalPlayer.PlayerScripts.CombatFramework))[2]['activeController']:attack()
        game:GetService'VirtualUser':CaptureController()
        game:GetService'VirtualUser':Button1Down(Vector2.new(1280, 672))
    end)
end)
game:GetService("RunService").Stepped:Connect(function()
    pcall(function()
        getupvalues(require(game:GetService("Players").LocalPlayer.PlayerScripts.CombatFramework))[2]['activeController']:attack()
        game:GetService'VirtualUser':CaptureController()
        game:GetService'VirtualUser':Button1Down(Vector2.new(1280, 672))
    end)
end)
game:GetService("RunService").Stepped:Connect(function()
    pcall(function()
        getupvalues(require(game:GetService("Players").LocalPlayer.PlayerScripts.CombatFramework))[2]['activeController']:attack()
        game:GetService'VirtualUser':CaptureController()
        game:GetService'VirtualUser':Button1Down(Vector2.new(1280, 672))
    end)
end)
game:GetService("RunService").Stepped:Connect(function()
    pcall(function()
        getupvalues(require(game:GetService("Players").LocalPlayer.PlayerScripts.CombatFramework))[2]['activeController']:attack()
        game:GetService'VirtualUser':CaptureController()
        game:GetService'VirtualUser':Button1Down(Vector2.new(1280, 672))
    end)
end)